env : "MetaWorld-v1"
num_symbolic_plans : "3"
num_actions_per_plan : "2"
deadline : "100"
verbose : "False"
version1 : "False"
seed : "40"
episodes : "200"
rollout_iterations : "1000"
lookahead_target : "100"
max_episode_steps : "1500"
cp : "10"