env : "MetaWorld-v1"
num_symbolic_plans : "2"
num_actions_per_plan : "2"
deadline : "36"
verbose : "False"
version1 : "False"
seed : "40"
episodes : "10"
rollout_iterations : "200"
lookahead_target : "100"
max_episode_steps : "1500"
cp : "5"