env : "MetaWorld-v1"
data_id : "2"
num_symbolic_plans : "2"
num_actions_per_plan : "2"
deadline : "40"
verbose : "False"
version1 : "False"
seed : "40"
episodes : "300"
rollout_iterations : "500"
lookahead_target : "100"
max_episode_steps : "1500"
cp : "10"