env : "PR2-v0"
logdir : "plots"
data_id : "4"
num_symbolic_plans : "2"
num_actions_per_plan : "1"
deadline : "10"
verbose : "False"
version1 : "False"
seed : "40"
episodes : "10"
rollout_iterations : "10"
lookahead_target : "100"
max_episode_steps : "1500"
cp : "5"